### ISSUE TITLE
share the 1-freepdk-45nm for each design

### ISSUE THREAD

**Issue by hanm2019** [mflowgen/mflowgen#137]
It seem that for each design, after I create a new directory, It need to download the master.zip file and unzip it. It would be better to create a link files so that multiple designs can share the same `1-freepdk-45nm` ?

**Comment by alexcarsello** [comment]
Yes, the provided freepdk-45nm adk node downloads the design files every time you run it. We opted to do this to make it simpler for users and because the download typically does not take very long. Most people end up setting up their own ADK for whatever technology they are using, and typically that ADK just links to files already present on their machine as you said.
